name: build

on:
  push:
    branches:
    - glslang
  pull_request:
    branches:
    - glslang

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Prepare repos
      run: ./scripts/gh-actions/add-vulkan-repo.sh
    - name: Install dependencies
      run: ./scripts/gh-actions/install-packages.sh
    - name: Setup
      run: meson setup build -Dbuild-tests=true
    - name: Build
      run: ninja -C build
    - name: Run tests
      run: meson test -v -C build
